spring:
  application:
    name: backend
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/lixo}
    username: ${DB_USERNAME:lixo_user}
    password: ${DB_PASSWORD:lixo_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}
